[2024-04-08 22:26:08,295: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-08 22:26:08,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-08 22:26:08,295: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-08 22:26:08,295: INFO: common: created directory at: artifacts]
[2024-04-08 22:26:08,295: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-08 22:26:08,295: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2024-04-08 22:26:08,438: INFO: data_ingestion: Extraction Compelete]
[2024-04-08 22:26:08,438: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-08 22:26:08,438: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-04-08 22:26:08,438: ERROR: main: name 'DataValidationPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    data_validation = DataValidationPipeline()
NameError: name 'DataValidationPipeline' is not defined
